### ISSUE TITLE
GetStations raising Unmarshal Error "json: cannot unmarshal string into Go value of type int "

### ISSUE THREAD

**Issue by adonnelly** [minchao/go-apple-music#2]
Hi, 

First of all great package, perfect for what I  need.  

I am getting an error when calling GetStation. 

```
id := "ra.1159500504"
stations, res, err := client.Catalog.GetStation(ctx, "gb", id, nil)
fmt.Printf("error: %v \n", err)
```

> error: json: cannot unmarshal string into Go value of type int 

The issue is here https://github.com/minchao/go-apple-music/blob/2a6f7042d9ac5841a20cc75c3af0a66333995dc3/catalog_stations.go#L18

The type for EpisodeNumber should be string to match the value returned in the response.

Cheers
Adrian

**Comment by minchao** [comment]
@adonnelly Thank you for reporting this issue.
In the Apple Music API document, that episodeNumber type is number, obviously one of them is wrong.

https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/AppleMusicWebServicesReference/Station.html#//apple_ref/doc/uid/TP40017625-CH52-SW1

**Comment by adonnelly** [comment]
I'd say its the documentation that's wrong :-) as its the first draft! I've checked a few stations and EpisodeNumber is always a string containing a number or empty string "".

**Comment by minchao** [comment]
Document updated: `string`

see https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/AppleMusicWebServicesReference/Station.html#//apple_ref/doc/uid/TP40017625-CH52-SW1
