### ISSUE TITLE
addOptions() nukes query params

### ISSUE THREAD

**Issue by vladcomp** [minchao/go-apple-music#7]
Query params added to the path prior to calling addOptions will get destroyed.  Calls such as GetSongsByIds will fail if options are included.

**Comment by minchao** [comment]
@vladcomp By design, should use addOptions() to add query params. :)

**Comment by vladcomp** [comment]
if by design then why does your GetSongsByIds method takes a list of IDs?

**Comment by minchao** [comment]
You are right, thanks for pointing it out.
