### ISSUE TITLE
Possible change to MusicKit API?

### ISSUE THREAD

**Issue by vladcomp** [minchao/go-apple-music#8]
Not sure what is going on, but all of a sudden I can no longer type assert a parsed resource into an **applemusic.Song** struct.  This code worked yesterday, and nothing has changed:

	for _, resource := range playlist.Relationships.Tracks.Data {

		res, err := resource.Parse()
		if err == nil {

			if song, ok := res.(*applemusic.Song); ok {
				
			}

but as of just now **ok** is always false.  Just wanted to make you aware of this. Cheers.

**Comment by minchao** [comment]
Thanks! I'll check it later. :)

**Comment by vladcomp** [comment]
Still seeing this issue. I've got a workaround of manually parsing the data if the type assertion fails.

**Comment by minchao** [comment]
Could you provide me the json data where the error occurred?

**Comment by vladcomp** [comment]
{"id":"i.gbPoTKBeq6","type":"library-songs","href":"/v1/me/library/songs/i.gbPoTKBeq6","attributes":{"artwork":{"width":1200,"height":1200,"url":"https://is2-ssl.mzstatic.com/image/thumb/Music/d5/34/a9/mzi.esilaluw.jpg/{w}x{h}bb.jpeg"},"artistName":"Zapp \u0026 Roger","genreNames":["R\u0026B/Soul"],"durationInMillis":312473,"releaseDate":"1980-01-01","name":"More Bounce to the Ounce","albumName":"Zapp \u0026 Roger: All the Greatest Hits","playParams":{"id":"i.gbPoTKBeq6","kind":"song","isLibrary":true,"reporting":true,"catalogId":"332672898"},"trackNumber":1}}

**Comment by minchao** [comment]
@vladcomp Thank you

It looks like requires two objects (LibrarySong and LibraryMusicVideo), see [properties of LibraryTrackRelationship](https://developer.apple.com/documentation/applemusicapi/librarytrackrelationship).

I have tried to [add them](https://github.com/minchao/go-apple-music/commit/f81e14d54a11f3f20f4741d4f93eabf784fb9f2a), but I don't have an Developer membership to test now, so please feel free to send a PR if you find any issues :P
